VERSION 0.7
start:
    LOCALLY
    
    DO +DEPS

    RUN kind create cluster --name earthlydemo-aio

    RUN kubectl apply -f ./all-in-one/earthly.yaml

    RUN sleep 15 # Let the cluster register the job

    RUN kubectl wait \
        --for=condition=ready \
        pod \
        -l app=earthly \
        --timeout=90s

    RUN kubectl logs -f jobs/earthly
    RUN kubectl apply -f ./all-in-one/nginx.yaml

clean:
    LOCALLY

    DO +DEPS

    RUN kind delete cluster --name earthlydemo-aio || true
    RUN kind delete cluster --name earthlydemo-remote || true

DEPS:
    COMMAND
    # Ensure local dependencies are present
    RUN which kind && which kubectl
