VERSION 0.7
start:
    LOCALLY
    
    DO +DEPS

    RUN kind create cluster --name earthlydemo-aio

    RUN kubectl apply -f ./all-in-one/earthly.yaml
    RUN kubectl apply -f ./all-in-one/nginx.yaml


    RUN sleep 15 # Let the cluster register the job

    RUN kubectl wait \
        --for=condition=ready \
        pod \
        -l app=earthly \
        --timeout=90s

    RUN kubectl logs -f jobs/earthly
    RUN kubectl get all -A
    RUN kubectl get pods
    RUN kubectl get deploy
    RUN terraform init
    RUN terraform plan
    RUN terraform apply --auto-approve

clean:
    LOCALLY

    DO +DEPS

    RUN kind delete cluster --name earthlydemo-aio || true
    RUN kind delete cluster --name earthlydemo-remote || true
    RUN terraform destroy --auto-approve
 

DEPS:
    COMMAND
    # Ensure local dependencies are present
    RUN which kind && which kubectl
